version: "3.8"
services:
  candidate-database:
    image: mysql:latest
    expose:
      - 3306
    volumes:
      - ./database-init:/docker-entrypoint-initdb.d
      - candidate-database-data:/var/lib/mysql
    env_file:
      - ./.database-env
    networks: 
      - ats-network
  candidate-service:
    image: miniats/candidate-service:latest
    expose: 
      - 8080
    volumes:
      - /tmp:/home/candidate-service/logs
    env_file:
      - ./.candidate-env
      - ./.discovery-env
    depends_on:
      - candidate-database
    networks: 
      - ats-network
volumes:
  candidate-database-data:
networks:
  ats-network:
    external:
      name: mini-ats-network
